### ISSUE TITLE
[question] Why build using a script?

### ISSUE THREAD

**Issue by bramus** [beejunk/universal-snowpack-example#3]
I'm wondering: why do you build using a separate script, instead of simply running `snowpack build`? Don't think the build script does any thing extra, or am I overlooking things?

**Comment by beejunk** [comment]
@bramus It's because the `snowpack.config.js` file is written as an ES module, and the snowpack CLI is expecting a Common JS module. If you run `npx snowpack build` in the project root it will show the following error:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /path/to/universal-snowpack-example/snowpack.config.js
require() of ES modules is not supported.
```
To get around this I wrote a custom build script that imports the config. I think it would be possible to write the config file as a Common JS module and rename it with the `.cjs` extension, which should work with the CLI. However, I thought it was more in the spirit of the project to write as much as possible using just ES modules.

**Comment by bramus** [comment]
Thanks; crystal clear now!

**Comment by beejunk** [comment]
@bramus : A recent Snowpack update fixed this issue, and now the CLI will recognize config files written using ES modules. So I've removed the build script and started using `snowpack build` directly.
